### ISSUE TITLE
Doesnt work in Greasemonkey (TypeError: GM.getResourceUrl is not a function)

### ISSUE THREAD

**Issue by Ezo** [ghostscript3r/poe-trade-official-site-enhancer#13]
Using Firefox 72.0.2 i get the following error:
Script error in [Greasemonkey script https://github.com/ghostscript3r/poe-trade-enhancer/poe-trade-official-site-enhancer; version 1.3.379]:
TypeError: GM.getResourceUrl is not a function

The script works when i use tampermonkey by the way

**Comment by ghostscript3r** [comment]
I'm well aware of the problem. 
Short answer, I'm not gonna support GM unless there's a lot of requests for it.
Here is why:
Basically GM in version 4 changed completely paradigm, moving to a completely asynchronous implementation. It's absolutely not a bad idea, probably it's the way to go for the future, but the way they did it it broke compatibility with everything else. I spent an awful lot of time trying to make the script work in both cases, but all I have to show for all that time is a lot of frustration. The libraries that should help doing this didn't work at all, the js console don't even show an error, the scripts just don't start.
I managed to make a script that works basically the same for two different trade tools, but I'll have to start over, almost from scratch, to make it work in GM. Considering that then I would be targeting mainly Firefox users only, I'm not really inclined to do this. 
The good thing is you can use both GM and TamperMonkey without any problem, so for the time being the only solution I have for you is to install both script managers. Sorry, but I really dedicated to this to much time already.

**Comment by Ezo** [comment]
I see. I dont mind using tampermonkey, but if you permanently dropped support for GM, it should be removed from the README.md

**Comment by ghostscript3r** [comment]
Thank you, I removed it from the about page but completely forgot to remove it from the readme file
