### ISSUE TITLE
Multi live search 4 of 5 sockets working

### ISSUE THREAD

**Issue by zlidenskardanom** [ghostscript3r/poe-trade-official-site-enhancer#28]
[Screenshot](https://sun9-72.userapi.com/1Wil877uFGCcSxw3lzkJ5LDVxAtcZV30TL1dtA/3L6EBtlOcsQ.jpg)
In 99% of cases, he does not look for pristine fossil, but sometimes he still loads it and everything works as it should, what is the reason?
I have included: 1 live search according to the standard and 5 through the poe trade enhancer

**Comment by ghostscript3r** [comment]
If you are in Chrome open the developer panel (F12) and check the network tab. There should be one or more red rows there, those are the requests your browser do to PoE server. It might contain details on the error. If I have to guess there's some sort of server side limitation if sometimes it works. If you try 5 different searches you might find it's always the fifth that have problems. If that is true I bet on server side limits in place.

**Comment by zlidenskardanom** [comment]
> Если вы находитесь в Chrome, откройте панель разработчика (F12) и проверьте вкладку Сеть. Там должна быть одна или несколько красных строк, это запросы, которые ваш браузер делает к PoE-серверу. Он может содержать сведения об ошибке. Если я должен догадаться, что есть какое-то ограничение на стороне сервера, если иногда это работает. Если вы попробуете 5 различных поисков, вы можете обнаружить, что это всегда пятый, у которого есть проблемы. Если это правда, то я ставлю на серверные ограничения на месте.

[Screenshot](https://sun9-42.userapi.com/fCC4-nIVrYuI_tR0pZUEyAUIars5D4A7Z2q3Cg/16t3erfPIgA.jpg)
All right, is there a way to eliminate it?

**Comment by ghostscript3r** [comment]
select WS or ALL and then look only at those in red. No Media is selected, it's not usefull to us. Also you will have to refresh the page to see the network stats.

**Comment by zlidenskardanom** [comment]
> select WS or ALL and then look only at those in red. No Media is selected, it's not usefull to us. Also you will have to refresh the page to see the network stats.

[Screenshot](https://sun9-4.userapi.com/yFEsbnr0xvXTtrTHph9XjpgXRU7vjXyMPgcPow/7tgNaJBK9dM.jpg)
Just wanted to try and fix the problem when I found it worked, amazing)
