### ISSUE TITLE
Issues with Expedition update

### ISSUE THREAD

**Issue by kareare** [ghostscript3r/poe-trade-official-site-enhancer#31]
There seem to be an issue since update hit. It was working fine just yesterday.
I can access the  settings menu (gear keeps turning), but screen buttons (saved searches, etc) are nowhere to be seen.

**Comment by boiledcrab** [comment]
![image](https://user-images.githubusercontent.com/87889700/126858487-1559d1c9-e3ed-4ec7-80b9-b189754dc63b.png)
Same issue.

**Comment by MatthewClair** [comment]
It looks like `persistant` was changed to `persistent` in the page

**Comment by kareare** [comment]
Thank you MatthewClair. That fixed it. 
I hope this tool isn't abandoned.

**Comment by boiledcrab** [comment]
True. MatthewClair saves the day. Changing persistant to persistent manually fixes the issue.

**Comment by TheOne320** [comment]
Every mention of persistant or just in specific places?

**Comment by AzsyGaming** [comment]
> Every mention of persistant or just in specific places?

Replaced all of them and it seems to be working again.

**Comment by redrios** [comment]
im having the same problem, what is the "page" referred to here, i'm not savvy in these subject (html/script/computer languages), when you say you fixed it, its on some code in ur browser/pc?
I tried reinstalling the same version, but the gear keeps rotating, and the page lacks all the "overlayed" text and things from the script

**Comment by TheOne320** [comment]
> 
> 
> im having the same problem, what is the "page" referred to here, i'm not savvy in these subject (html/script/computer languages), when you say you fixed it, its on some code in ur browser/pc?
> I tried reinstalling the same version, but the gear keeps rotating, and the page lacks all the "overlayed" text and things from the script

You have to open the script in Tampermonkey and then you can replace all mentions of "persistant" with "persistent".
![image](https://user-images.githubusercontent.com/7705568/126903400-80eb5c7f-cc28-4748-b3e9-ad4d2bc24522.png)

**Comment by redrios** [comment]
ok, so, 1 hour of researching whats what and then when found 5 min to figure out how to, thanks! I see now this, hehe. I forgot i had the thing store locally in my pc, somehow i thought it was cloudbased

**Comment by ghostscript3r** [comment]
Thank you MatthewClair for the quick fix! The tool is not abandoneware even if I didn't release new features for a while, I just was on holidays for 3.15 launch. I'll try to fix this in the next few days, hopefully with a new feature for map searching based on regions/awakening I've been working on for a while (I started playing again only at the end of 3.14).

**Comment by ghostscript3r** [comment]
Finally had the time to release this fix along the new feature.
