### ISSUE TITLE
Error An error prevented PTE from saving the current search in your browser local storage.

### ISSUE THREAD

**Issue by Lucar77** [ghostscript3r/poe-trade-official-site-enhancer#35]
Guys, I don't know what happened but the extension stopped working and gives the error 'Error
An error prevented PTE from saving the current search in your browser local storage'. Whenever I try to save, delete or no action. I've removed everything and reinstalled and it didn't solve. On the poe.trade site the other expansion works fine, but the site officer stopped.

I hope you help me and I thank you for all the excellent work and forgive my English.
![2021-08-11 14 57 23 www pathofexile com b08dea976c5c](https://user-images.githubusercontent.com/5124984/129079717-ebdaea48-315b-4910-b4e5-a63e5a3b4e23.jpg)
![2021-08-11 14 57 54 www pathofexile com 721053ff7edc](https://user-images.githubusercontent.com/5124984/129079719-abd1d241-599c-4c99-b5cd-f6b7fd642cc6.jpg)

**Comment by ghostscript3r** [comment]
Yes, I saw it this morning. Update to 1.4.14, it's already solved. The bug was introduced in the new map selector
