### ISSUE TITLE
Saving/Loading searches between official site and poetrade

### ISSUE THREAD

**Issue by Azdingo** [ghostscript3r/poe-trade-official-site-enhancer#8]
I installed both scripts (official site and poetrade) and exported my searches from the official site and imported them in poetrade.

I see all of them, but once I click on one (to load it), all the fields are blank.

Is this suppose to work or are they saved in different format?

**Comment by ghostscript3r** [comment]
They are in different format. I have it in roadmap but I frankly have no idea when or even if I'll be able to get to it. It has also never been voted by anyone here: https://www.tricider.com/admin/36HWcTk5RhZ/DawSV0oQX7b
